"use client";

import { useState } from "react";
import { CalendarClock, Sparkles, CheckCircle2, AlertTriangle, Clock, Target, Download, ChevronDown, ChevronUp } from "lucide-react";
import styles from "./page.module.css";
import { useLanguage } from "@/context/LanguageContext";
import { useGravity } from "@/context/GravityContext";
import InfoTooltip from "@/components/InfoTooltip";

interface Milestone {
    phase: string;
    monthOffset: number;
    title: string;
    description: string;
    keyActions: string[];
    kpis: string[];
    budget: number;
}

interface CriticalDeadline {
    date: string;
    title: string;
    description: string;
    urgency: "high" | "medium" | "low";
}

interface TimelineResult {
    milestones: Milestone[];
    criticalDeadlines: CriticalDeadline[];
    recommendations: string[];
}

export default function TimelinePage() {
    const { t, lang } = useLanguage();
    const { seed, completeStep } = useGravity();
    const [startDate, setStartDate] = useState("");
    const [campaignType, setCampaignType] = useState<"Impact" | "Maintenance">("Impact");
    const [market, setMarket] = useState("");
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState<TimelineResult | null>(null);
    const [error, setError] = useState("");
    const [expandedPhase, setExpandedPhase] = useState<number | null>(null);

    const handleGenerate = async (e: React.FormEvent) => {
        e.preventDefault();
        setError("");
        setResult(null);
        setLoading(true);

        try {
            const response = await fetch('/api/ai/timeline', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    seed,
                    campaignType,
                    startDate,
                    market: market || undefined,
                    lang
                })
            });

            if (!response.ok) {
                throw new Error('Failed to generate timeline');
            }

            const data = await response.json();
            setResult(data);
            completeStep("timeline", data);
        } catch (err) {
            console.error("Timeline generation error:", err);
            setError(lang === "es"
                ? "Error al generar la hoja de ruta. Intente de nuevo."
                : lang === "ca"
                    ? "Error en generar el full de ruta. Torneu-ho a intentar."
                    : "Error generating roadmap. Please try again.");
        } finally {
            setLoading(false);
        }
    };

    const getDateFromOffset = (monthOffset: number) => {
        if (!startDate) return "";
        const date = new Date(startDate);
        date.setMonth(date.getMonth() + monthOffset);
        return date.toLocaleDateString(lang === 'es' ? 'es-ES' : lang === 'ca' ? 'ca-ES' : 'en-US', {
            year: 'numeric',
            month: 'long'
        });
    };

    const getUrgencyColor = (urgency: string) => {
        switch (urgency) {
            case "high": return "#ef4444";
            case "medium": return "#f59e0b";
            case "low": return "#22c55e";
            default: return "#94a3b8";
        }
    };

    const handleExport = () => {
        if (!result) return;

        const content = `
EUROMED INTELPLANNER - TIMELINE ROADMAP
=======================================
Date: ${new Date().toLocaleDateString()}
Asset: ${seed}
Campaign Type: ${campaignType}
Start Date: ${startDate}
${market ? `Market: ${market}` : ""}

MILESTONES
----------
${result.milestones.map((m, idx) => `
[${m.phase}] ${m.title}
Date: ${getDateFromOffset(m.monthOffset)}
Budget: ${m.budget}%

${m.description}

Key Actions:
${m.keyActions.map(a => `  • ${a}`).join('\n')}

KPIs:
${m.kpis.map(k => `  • ${k}`).join('\n')}
`).join('\n---\n')}

CRITICAL DEADLINES
------------------
${result.criticalDeadlines.map(d => `
[${d.urgency.toUpperCase()}] ${d.title}
Date: ${d.date}
${d.description}
`).join('\n')}

STRATEGIC RECOMMENDATIONS
-------------------------
${result.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

=======================================
Generated by Euromed IntelPlanner AI
`;
        const blob = new Blob([content], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `Timeline_${seed}_${new Date().toISOString().split('T')[0]}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    return (
        <div className={styles.container}>
            <header className={styles.header}>
                <div className={styles.iconWrapper}>
                    <CalendarClock size={40} />
                </div>
                <div>
                    <h1 className={styles.title}>
                        {seed && <span style={{ opacity: 0.7 }}>{seed}: </span>}
                        {t("temporalProgramming")}
                    </h1>
                    <p className={styles.subtitle}>{t("timelineSubtitle")}</p>
                </div>
            </header>

            <div className={styles.content}>
                {/* Input Panel */}
                <section className={`${styles.panel} glass-panel`}>
                    <h2 className={styles.panelTitle}>{t("roadmapConfig")}</h2>
                    <form onSubmit={handleGenerate} className={styles.form}>
                        <div className={styles.inputGroup}>
                            <label className={styles.label}>
                                {t("campaignType") || "Campaign Type"}
                                <InfoTooltip content={t("tooltipCampaignType")} />
                            </label>
                            <select
                                className={styles.input}
                                value={campaignType}
                                onChange={e => setCampaignType(e.target.value as "Impact" | "Maintenance")}
                            >
                                <option value="Impact">
                                    {lang === "es" ? "Impacto (Lanzamiento/Crecimiento)" :
                                        lang === "ca" ? "Impacte (Llançament/Creixement)" :
                                            "Impact (Launch/Growth)"}
                                </option>
                                <option value="Maintenance">
                                    {lang === "es" ? "Mantenimiento (Fidelización)" :
                                        lang === "ca" ? "Manteniment (Fidelització)" :
                                            "Maintenance (Retention)"}
                                </option>
                            </select>
                        </div>
                        <div className={styles.inputGroup}>
                            <label className={styles.label}>{t("campaignStart")}</label>
                            <input
                                className={styles.input}
                                type="date"
                                value={startDate}
                                onChange={e => setStartDate(e.target.value)}
                                required
                            />
                        </div>
                        <div className={styles.inputGroup}>
                            <label className={styles.label}>
                                {lang === "es" ? "Mercado (opcional)" :
                                    lang === "ca" ? "Mercat (opcional)" :
                                        "Market (optional)"}
                            </label>
                            <input
                                className={styles.input}
                                type="text"
                                value={market}
                                onChange={e => setMarket(e.target.value)}
                                placeholder={lang === "es" ? "Ej: Europa, USA" :
                                    lang === "ca" ? "Ex: Europa, USA" :
                                        "e.g. Europe, USA"}
                            />
                        </div>

                        {error && (
                            <div className={styles.errorBox}>
                                <AlertTriangle size={20} />
                                <p>{error}</p>
                            </div>
                        )}

                        <button type="submit" className={`glass-button ${styles.submitBtn}`} disabled={loading}>
                            {loading ? (
                                <span className={styles.generating}>
                                    <Sparkles size={18} className={styles.spin} />
                                    {lang === "es" ? "Generando hoja de ruta..." :
                                        lang === "ca" ? "Generant full de ruta..." :
                                            "Generating roadmap..."}
                                </span>
                            ) : t("generateRoadmap")}
                        </button>
                    </form>

                    {/* Seed reminder */}
                    <div className={styles.seedReminder}>
                        <Target size={16} />
                        <span>
                            {lang === "es" ? `Generando para: ${seed || "Sin definir"}` :
                                lang === "ca" ? `Generant per a: ${seed || "Sense definir"}` :
                                    `Generating for: ${seed || "Not defined"}`}
                        </span>
                    </div>
                </section>

                {/* Results Panel */}
                {result && (
                    <section className={`${styles.timelineWrapper} glass-panel`}>
                        {/* Critical Deadlines */}
                        {result.criticalDeadlines && result.criticalDeadlines.length > 0 && (
                            <div className={styles.deadlinesSection}>
                                <h3 className={styles.sectionTitle}>
                                    <AlertTriangle size={18} />
                                    {lang === "es" ? "Deadlines Críticos" :
                                        lang === "ca" ? "Deadlines Crítics" :
                                            "Critical Deadlines"}
                                </h3>
                                <div className={styles.deadlinesGrid}>
                                    {result.criticalDeadlines.map((d, idx) => (
                                        <div
                                            key={idx}
                                            className={styles.deadlineCard}
                                            style={{ borderLeftColor: getUrgencyColor(d.urgency) }}
                                        >
                                            <div className={styles.deadlineHeader}>
                                                <span className={styles.deadlineDate}>{d.date}</span>
                                                <span
                                                    className={styles.urgencyBadge}
                                                    style={{ backgroundColor: getUrgencyColor(d.urgency) }}
                                                >
                                                    {d.urgency.toUpperCase()}
                                                </span>
                                            </div>
                                            <h4 className={styles.deadlineTitle}>{d.title}</h4>
                                            <p className={styles.deadlineDesc}>{d.description}</p>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                        {/* Timeline */}
                        <div className={styles.timeline}>
                            {result.milestones.map((m, idx) => (
                                <div key={idx} className={styles.timelineItem}>
                                    <div className={styles.timelineMarker}>
                                        <div className={styles.markerCircle}>
                                            <CheckCircle2 size={16} />
                                        </div>
                                        {idx < result.milestones.length - 1 && (
                                            <div className={styles.markerLine}></div>
                                        )}
                                    </div>
                                    <div className={styles.timelineContent}>
                                        <div className={styles.timelineHeader}>
                                            <span className={styles.timelineDate}>
                                                <Clock size={14} />
                                                {getDateFromOffset(m.monthOffset)}
                                            </span>
                                            <span className={styles.budgetBadge}>{m.budget}%</span>
                                        </div>
                                        <h3 className={styles.timelineTitle}>
                                            {m.title}
                                            <span className={styles.timelinePhase}>({m.phase})</span>
                                        </h3>
                                        <p className={styles.timelineDesc}>{m.description}</p>

                                        <button
                                            className={styles.expandBtn}
                                            onClick={() => setExpandedPhase(expandedPhase === idx ? null : idx)}
                                        >
                                            {expandedPhase === idx ? (
                                                <>
                                                    <ChevronUp size={16} />
                                                    {lang === "es" ? "Ver menos" : lang === "ca" ? "Veure menys" : "Show less"}
                                                </>
                                            ) : (
                                                <>
                                                    <ChevronDown size={16} />
                                                    {lang === "es" ? "Ver acciones y KPIs" : lang === "ca" ? "Veure accions i KPIs" : "Show actions & KPIs"}
                                                </>
                                            )}
                                        </button>

                                        {expandedPhase === idx && (
                                            <div className={styles.expandedContent}>
                                                <div className={styles.actionsSection}>
                                                    <h4>
                                                        {lang === "es" ? "Acciones Clave" :
                                                            lang === "ca" ? "Accions Clau" :
                                                                "Key Actions"}
                                                    </h4>
                                                    <ul>
                                                        {m.keyActions.map((action, i) => (
                                                            <li key={i}>{action}</li>
                                                        ))}
                                                    </ul>
                                                </div>
                                                <div className={styles.kpisSection}>
                                                    <h4>KPIs</h4>
                                                    <ul>
                                                        {m.kpis.map((kpi, i) => (
                                                            <li key={i}>{kpi}</li>
                                                        ))}
                                                    </ul>
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                </div>
                            ))}
                        </div>

                        {/* Recommendations */}
                        {result.recommendations && result.recommendations.length > 0 && (
                            <div className={styles.recommendationsSection}>
                                <h3 className={styles.sectionTitle}>
                                    <Target size={18} />
                                    {lang === "es" ? "Recomendaciones Estratégicas" :
                                        lang === "ca" ? "Recomanacions Estratègiques" :
                                            "Strategic Recommendations"}
                                </h3>
                                <ul className={styles.recommendationsList}>
                                    {result.recommendations.map((rec, idx) => (
                                        <li key={idx}>{rec}</li>
                                    ))}
                                </ul>
                            </div>
                        )}

                        {/* Export Button */}
                        <button onClick={handleExport} className={styles.exportBtn}>
                            <Download size={18} />
                            {lang === "es" ? "Descargar Hoja de Ruta" :
                                lang === "ca" ? "Descarregar Full de Ruta" :
                                    "Download Roadmap"}
                        </button>
                    </section>
                )}
            </div>
        </div>
    );
}
